export const Countries = [
    { "id": "JPN", "label": "Japan" },
    { "id": "IND", "label": "India" },
    { "id": "VNM", "label": "Vietnam" },
    { "id": "IDN", "label": "Indonesia" },
    { "id": "MYS", "label": "Malaysia" },
    { "id": "PHL", "label": "Philippines" },
    { "id": "HKG", "label": "Hong Kong" },
    { "id": "SGP", "label": "Singapore" },
    { "id": "AUS", "label": "Australia" },
    { "id": "CHN", "label": "China" },
    { "id": "AFG", "label": "Afghanistan" },
    { "id": "ALB", "label": "Albania" },
    { "id": "DZA", "label": "Algeria" },
    { "id": "ASM", "label": "American Samoa" },
    { "id": "AND", "label": "Andorra" },
    { "id": "AGO", "label": "Angola" },
    { "id": "AIA", "label": "Anguilla" },
    { "id": "ATA", "label": "Antarctica" },
    { "id": "ATG", "label": "Antigua and Barbuda" },
    { "id": "ARG", "label": "Argentina" },
    { "id": "ARM", "label": "Armenia" },
    { "id": "ABW", "label": "Aruba" },
    { "id": "AUT", "label": "Austria" },
    { "id": "AZE", "label": "Azerbaijan" },
    { "id": "BHS", "label": "Bahamas" },
    { "id": "BHR", "label": "Bahrain" },
    { "id": "BGD", "label": "Bangladesh" },
    { "id": "BRB", "label": "Barbados" },
    { "id": "BLR", "label": "Belarus" },
    { "id": "BEL", "label": "Belgium" },
    { "id": "BLZ", "label": "Belize" },
    { "id": "BEN", "label": "Benin" },
    { "id": "BMU", "label": "Bermuda" },
    { "id": "BTN", "label": "Bhutan" },
    { "id": "BOL", "label": "Bolivia (Plurinational State of)" },
    { "id": "BES", "label": "Bonaire (Saint Eustatius and Saba)" },
    { "id": "BIH", "label": "Bosnia and Herzegovina" },
    { "id": "BWA", "label": "Botswana" },
    { "id": "BVT", "label": "Bouvet Island" },
    { "id": "BRA", "label": "Brazil" },
    { "id": "IOT", "label": "British Indian Ocean Territory" },
    { "id": "BRN", "label": "Brunei Darussalam" },
    { "id": "BGR", "label": "Bulgaria" },
    { "id": "BFA", "label": "Burkina Faso" },
    { "id": "BDI", "label": "Burundi" },
    { "id": "KHM", "label": "Cambodia" },
    { "id": "CMR", "label": "Cameroon" },
    { "id": "CAN", "label": "Canada" },
    { "id": "CPV", "label": "Cape Verde" },
    { "id": "CYM", "label": "Cayman Islands" },
    { "id": "CAF", "label": "Central African Republic" },
    { "id": "TCD", "label": "Chad" },
    { "id": "CHL", "label": "Chile" },
    { "id": "CXR", "label": "Christmas Island" },
    { "id": "CCK", "label": "Cocos (Keeling) Islands" },
    { "id": "COL", "label": "Colombia" },
    { "id": "COM", "label": "Comoros" },
    { "id": "COG", "label": "Congo" },
    { "id": "COD", "label": "Congo (The Democratic Republic of the)" },
    { "id": "COK", "label": "Cook Islands" },
    { "id": "CRI", "label": "Costa Rica" },
    { "id": "HRV", "label": "Croatia" },
    { "id": "CUB", "label": "Cuba" },
    { "id": "CUW", "label": "Curacao" },
    { "id": "CYP", "label": "Cyprus" },
    { "id": "CZE", "label": "Czech Republic" },
    { "id": "CIV", "label": "Cote d'Ivoire" },
    { "id": "DNK", "label": "Denmark" },
    { "id": "DJI", "label": "Djibouti" },
    { "id": "DMA", "label": "Dominica" },
    { "id": "DOM", "label": "Dominican Republic" },
    { "id": "ECU", "label": "Ecuador" },
    { "id": "EGY", "label": "Egypt" },
    { "id": "SLV", "label": "El Salvador" },
    { "id": "GNQ", "label": "Equatorial Guinea" },
    { "id": "ERI", "label": "Eritrea" },
    { "id": "EST", "label": "Estonia" },
    { "id": "ETH", "label": "Ethiopia" },
    { "id": "FLK", "label": "Falkland Islands (Malvinas)" },
    { "id": "FRO", "label": "Faroe Islands" },
    { "id": "FJI", "label": "Fiji" },
    { "id": "FIN", "label": "Finland" },
    { "id": "FRA", "label": "France" },
    { "id": "GUF", "label": "French Guiana" },
    { "id": "PYF", "label": "French Polynesia" },
    { "id": "ATF", "label": "French Southern Territories" },
    { "id": "GAB", "label": "Gabon" },
    { "id": "GMB", "label": "Gambia" },
    { "id": "GEO", "label": "Georgia" },
    { "id": "DEU", "label": "Germany" },
    { "id": "GHA", "label": "Ghana" },
    { "id": "GIB", "label": "Gibraltar" },
    { "id": "GRC", "label": "Greece" },
    { "id": "GRL", "label": "Greenland" },
    { "id": "GRD", "label": "Grenada" },
    { "id": "GLP", "label": "Guadeloupe" },
    { "id": "GUM", "label": "Guam" },
    { "id": "GTM", "label": "Guatemala" },
    { "id": "GGY", "label": "Guernsey" },
    { "id": "GIN", "label": "Guinea" },
    { "id": "GNB", "label": "Guinea-Bissau" },
    { "id": "GUY", "label": "Guyana" },
    { "id": "HTI", "label": "Haiti" },
    { "id": "HMD", "label": "Heard Island and McDonald Islands" },
    { "id": "VAT", "label": "Holy See (Vatican City State)" },
    { "id": "HND", "label": "Honduras" },
    { "id": "HUN", "label": "Hungary" },
    { "id": "ISL", "label": "Iceland" },
    { "id": "IRN", "label": "Iran (The Islamic Republic of)" },
    { "id": "IRQ", "label": "Iraq" },
    { "id": "IRL", "label": "Ireland" },
    { "id": "IMN", "label": "Isle of Man" },
    { "id": "ISR", "label": "Israel" },
    { "id": "ITA", "label": "Italy" },
    { "id": "JAM", "label": "Jamaica" },
    { "id": "JEY", "label": "Jersey" },
    { "id": "JOR", "label": "Jordan" },
    { "id": "KAZ", "label": "Kazakhstan" },
    { "id": "KEN", "label": "Kenya" },
    { "id": "KIR", "label": "Kiribati" },
    { "id": "PRK", "label": "North Korea" },
    { "id": "KOR", "label": "South Korea" },
    { "id": "KWT", "label": "Kuwait" },
    { "id": "KGZ", "label": "Kyrgyzstan" },
    { "id": "LAO", "label": "Laos" },
    { "id": "LVA", "label": "Latvia" },
    { "id": "LBN", "label": "Lebanon" },
    { "id": "LSO", "label": "Lesotho" },
    { "id": "LBR", "label": "Liberia" },
    { "id": "LBY", "label": "Libyan Arab Jamahiriya" },
    { "id": "LIE", "label": "Liechtenstein" },
    { "id": "LTU", "label": "Lithuania" },
    { "id": "LUX", "label": "Luxembourg" },
    { "id": "MAC", "label": "Macao" },
    { "id": "MKD", "label": "Macedonia (The former Yugoslav Republic)" },
    { "id": "MDG", "label": "Madagascar" },
    { "id": "MWI", "label": "Malawi" },
    { "id": "MDV", "label": "Maldives" },
    { "id": "MLI", "label": "Mali" },
    { "id": "MLT", "label": "Malta" },
    { "id": "MHL", "label": "Marshall Islands" },
    { "id": "MTQ", "label": "Martinique" },
    { "id": "MRT", "label": "Mauritania" },
    { "id": "MUS", "label": "Mauritius" },
    { "id": "MYT", "label": "Mayotte" },
    { "id": "MEX", "label": "Mexico" },
    { "id": "FSM", "label": "Micronesia (The Federated States of)" },
    { "id": "MDA", "label": "Moldova (The Republic of)" },
    { "id": "MCO", "label": "Monaco" },
    { "id": "MNG", "label": "Mongolia" },
    { "id": "MNE", "label": "Montenegro" },
    { "id": "MSR", "label": "Montserrat" },
    { "id": "MAR", "label": "Morocco" },
    { "id": "MOZ", "label": "Mozambique" },
    { "id": "MMR", "label": "Myanmar" },
    { "id": "NAM", "label": "Namibia" },
    { "id": "NRU", "label": "Nauru" },
    { "id": "NPL", "label": "Nepal" },
    { "id": "NLD", "label": "Netherlands" },
    { "id": "NCL", "label": "New Caledonia" },
    { "id": "NZL", "label": "New Zealand" },
    { "id": "NIC", "label": "Nicaragua" },
    { "id": "NER", "label": "Niger" },
    { "id": "NGA", "label": "Nigeria" },
    { "id": "NIU", "label": "Niue" },
    { "id": "NFK", "label": "Norfolk Island" },
    { "id": "MNP", "label": "Northern Mariana Islands" },
    { "id": "NOR", "label": "Norway" },
    { "id": "OMN", "label": "Oman" },
    { "id": "PAK", "label": "Pakistan" },
    { "id": "PLW", "label": "Palau" },
    { "id": "PSE", "label": "Palestinian Territory (Occupied)" },
    { "id": "PAN", "label": "Panama" },
    { "id": "PNG", "label": "Papua New Guinea" },
    { "id": "PRY", "label": "Paraguay" },
    { "id": "PER", "label": "Peru" },
    { "id": "PCN", "label": "Pitcairn" },
    { "id": "POL", "label": "Poland" },
    { "id": "PRT", "label": "Portugal" },
    { "id": "PRI", "label": "Puerto Rico" },
    { "id": "QAT", "label": "Qatar" },
    { "id": "REU", "label": "Reunion" },
    { "id": "ROU", "label": "Romania" },
    { "id": "RUS", "label": "Russian Federation" },
    { "id": "RWA", "label": "Rwanda" },
    { "id": "BLM", "label": "Saint Barthelemy" },
    { "id": "SHN", "label": "Saint Helena (Ascension and Tristan da Cunha)" },
    { "id": "KNA", "label": "Saint Kitts and Nevis" },
    { "id": "LCA", "label": "Saint Lucia" },
    { "id": "MAF", "label": "Saint Martin (French)" },
    { "id": "SPM", "label": "Saint Pierre and Miquelon" },
    { "id": "VCT", "label": "Saint Vincent and the Grenadines" },
    { "id": "WSM", "label": "Samoa" },
    { "id": "SMR", "label": "San Marino" },
    { "id": "STP", "label": "Sao Tome and Principe" },
    { "id": "SAU", "label": "Saudi Arabia" },
    { "id": "SEN", "label": "Senegal" },
    { "id": "SRB", "label": "Serbia" },
    { "id": "SYC", "label": "Seychelles" },
    { "id": "SLE", "label": "Sierra Leone" },
    { "id": "SXM", "label": "Sint Maarten (Dutch)" },
    { "id": "SVK", "label": "Slovakia" },
    { "id": "SVN", "label": "Slovenia" },
    { "id": "SLB", "label": "Solomon Islands" },
    { "id": "SOM", "label": "Somalia" },
    { "id": "ZAF", "label": "South Africa" },
    { "id": "SGS", "label": "South Georgia and the South Sandwich Islands" },
    { "id": "SSD", "label": "South Sudan" },
    { "id": "ESP", "label": "Spain" },
    { "id": "LKA", "label": "Sri Lanka" },
    { "id": "SDN", "label": "Sudan" },
    { "id": "SUR", "label": "Suriname" },
    { "id": "SJM", "label": "Svalbard and Jan Mayen" },
    { "id": "SWZ", "label": "Swaziland" },
    { "id": "SWE", "label": "Sweden" },
    { "id": "CHE", "label": "Switzerland" },
    { "id": "SYR", "label": "Syrian Arab Republic" },
    { "id": "TWN", "label": "Taiwan" },
    { "id": "TJK", "label": "Tajikistan" },
    { "id": "TZA", "label": "Tanzania (The United Republic of)" },
    { "id": "THA", "label": "Thailand" },
    { "id": "TLS", "label": "Timor-Leste" },
    { "id": "TGO", "label": "Togo" },
    { "id": "TKL", "label": "Tokelau" },
    { "id": "TON", "label": "Tonga" },
    { "id": "TTO", "label": "Trinidad and Tobago" },
    { "id": "TUN", "label": "Tunisia" },
    { "id": "TUR", "label": "Turkey" },
    { "id": "TKM", "label": "Turkmenistan" },
    { "id": "TCA", "label": "Turks and Caicos Islands" },
    { "id": "TUV", "label": "Tuvalu" },
    { "id": "UGA", "label": "Uganda" },
    { "id": "UKR", "label": "Ukraine" },
    { "id": "ARE", "label": "United Arab Emirates" },
    { "id": "GBR", "label": "United Kingdom" },
    { "id": "USA", "label": "United States" },
    { "id": "UMI", "label": "United States Minor Outlying Islands" },
    { "id": "URY", "label": "Uruguay" },
    { "id": "UZB", "label": "Uzbekistan" },
    { "id": "VUT", "label": "Vanuatu" },
    { "id": "VEN", "label": "Venezuela (The Bolivarian Republic of)" },
    { "id": "VGB", "label": "Virgin Islands (British)" },
    { "id": "VIR", "label": "Virgin Islands (U.S.)" },
    { "id": "WLF", "label": "Wallis and Futuna" },
    { "id": "ESH", "label": "Western Sahara" },
    { "id": "YEM", "label": "Yemen" },
    { "id": "ZMB", "label": "Zambia" },
    { "id": "ZWE", "label": "Zimbabwe" },
    { "id": "ALA", "label": "Aland Islands" }
];